version: "3"
services:
  couch-1.6:
    image: klaemo/couchdb:1.6
    env_file: environment
    ports:
      - "6016:5984"
  couch-2.1.0:
    build: couchdb-2.1
    env_file: environment
    ports:
      - "6020:5984"
